name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Unit-Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Link SwiftLint or install it
        run: brew link --overwrite swiftlint || brew install swiftlint

      - name: Set up XCode 
        run: sudo xcode-select --switch /Applications/Xcode_15.0.app
      
      - name: Bundle Install
        run: bundle install
      
      - name: Unit tests
        run: bundle exec fastlane unit_tests
      
      - name: Code Coverage
        run: bundle exec fastlane coverage
      
      - name: Lint
        run: bundle exec fastlane lint